version: "3"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: awtarcontainerregistery.azurecr.io/awtar-backend-api:latest
    command: sh -c "python manage.py makemigrations && python manage.py makemigrations music && python manage.py migrate && python manage.py migrate music && python manage.py migrate --run-syncdb && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - db
    environment:
      - SECRET_KEY=EB94C941DCE1455DA48A2CE2F8BEAF50B98704B92B163544AD64DEDEB665C6A2
      - DEBUG=True
      - URL=0.0.0.0,127.0.0.1,localhost
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - LOCAL=True

volumes:
  postgres_data: