# Generated by Django 4.2.6 on 2023-10-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_favouritesmodel_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritesmodel',
            name='track_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.tracksmodel'),
        ),
    ]
